name: Update Checkuit in Codespaces

on:
  push:
    branches:
      - main

jobs:
  update_checkuit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfile Repository
        uses: actions/checkout@v2

      - name: Clone Checkuit Repository
        run: |
          git clone https://github.com/generallprince/checkuit.git /workspaces/checkuit
          cd /workspaces/checkuit
          git pull origin main

      - name: Notify Codespaces
        run: |
          echo "Checkuit updated in Codespaces."
